name: orange_eats_offline_full
description: Uber Eats–style app (EN/AR), offline-first with Hive caching, mock API assets, QR + Favorites, Cart, Orders
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_riverpod: ^2.5.1
  dio: ^5.6.0
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/i18n/en.json
    - assets/i18n/ar.json
    - assets/data/demo_restaurant.json
